name: Create Release

on:
  push:
    tags:
      - 'v*'  # v1.0.0, v2.1.3 などのタグにマッチ

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create release archive
      run: |
        # 不要なファイルを除外してzipを作成
        zip -r git-maintenance-${{ github.ref_name }}.zip . \
          -x "*.git*" \
          -x "*.github*" \
          -x "README.md" \
          -x "*.zip"
        
        # バージョン情報を含むファイルを作成
        echo "Version: ${{ github.ref_name }}" > VERSION.txt
        echo "Build Date: $(date)" >> VERSION.txt
        echo "Commit: ${{ github.sha }}" >> VERSION.txt
        
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref_name }}
        body: |
          ## 変更点
          - 詳細な変更点をここに記載
          
          ## インストール方法
          1. 添付のzipファイルをダウンロード
          2. 適当なフォルダに展開
          3. setup.bat を実行して初期設定
          
          ## 注意事項
          - このバージョンでは7z.exeが必須です
          - Windows環境でのみ動作します
        draft: false
        prerelease: false
        
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./git-maintenance-${{ github.ref_name }}.zip
        asset_name: git-maintenance-${{ github.ref_name }}.zip
        asset_content_type: application/zip
